version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_api
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "pgsql://symfony:symfony@db:5432/symfony"
    networks:
      - app-network
    command: php -S 0.0.0.0:8000 -t public

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: expo_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "19000:19000"   # Expo Dev Tools
      - "19001:19001"   # WebSocket (LAN)
      - "19002:19002"   # Expo Web
      - "8081:8081"     # Metro Bundler
    networks:
      - app-network
    stdin_open: true
    tty: true
    command: ["npx", "expo", "start", "--lan", "-c"]

  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
